export interface IReglamentInterface {
  id?: number | any;
  program: string;
  initialPeriod: string;
  isOpenPeriod: boolean;
  endPeriod?: string | any;
  theoreticalSemiannualPercent: number;
  applySocialService: boolean;
  socialServicePercent?: number | any;
  socialServiceHours?: number | any;
  applyKnowledgeTransfer: boolean;
  knowledgeTransferPercent?: number | any;
  knowledgeTransferHours?: number | any;
  applyGracePeriod: boolean;
  gracePeriodMonths?: number | any;
  graceDateApplication?: string | any;
  applyContinuousSuspension: boolean;
  continuosSuspencionQuantity?: number | any;
  applyDiscontinuousSuspension: boolean;
  discontinuousSuspensionQuantity?: number | any;
  applySpecialSuspensions: boolean;
  specialSuspensionsQuantity?: number | any;
  applyExtension: boolean;
  extensionQuantity?: number | any;
  applyCondonationPerformancePeriod: boolean;
  periodPerformance?: string | any;
  performancePeriod?: string | any;
  applyAccomulatedIncomeCondonation: boolean;
  accomulatedPerformance?: string | any;
  accumulatedPerformance?: string | any;
  modifyUser?: string;
  modifyDate?: string;
  createUser: string;
  createDate: string;
}
